[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "html_to_text"
version = "0.11"
description = "Converts HTML to text"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "lxml",
]